### ISSUE TITLE
Add Role text to the draft re: components

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-arch#11]
At the September virtual interim, Henk mentioned that the components in Figure 2 could be "rolled up" into just a few software components, correctly recognizing that any of the boxes in the diagram could exist in one or many pieces of software. As such, he views the boxes more as indicating roles more than components.
NOTE: Henk offered to provide text.

**Comment by wmunyan** [comment]
reorganized the draft in the -04 version.  Draft begins with a more "rolled up" diagram and then breaks them up into roles.  marking as complete in -04
