### ISSUE TITLE
Reordering of the draft

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-arch#13]
During the September virtual interim, Henk suggested that the ordering of the draft may be off. The interaction section seems to be deep-diving suddenly through a bunch of different layers, then stops abruptly and switches to section 6.

Adam asked Henk to propose a specific change in this regard. The gist is to move the basic things the components have to do with each other to build a functional system earlier in the draft, before the target endpoint information/assessment material.

**Comment by wmunyan** [comment]
Similar to #11 draft has been updated in -04 to reorganize the draft, and move the assessment/workflow stuff to after the role/component discussions.  Marking as complete for -04
