### ISSUE TITLE
Substitute enterprise boundary with ecosystem boundary

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-arch#18]
Wherever the draft talks about the enterprise boundary, we should update the term to be the ecosystem boundary.

**Comment by adammontville** [comment]
I received an off-list suggestion to use term _responsibility domain_ instead of _ecosystem boundary_. The argument put forth is essentially that the term ecosystem isn’t really used to describe architectural boundaries. 

I think what we were going after in making this change is to explicitly recognize that the computing resources used by an enterprise today may include endpoints (in the traditional sense), and other computing resources such as non-enterprise devices (BYOD), and resources that are part of a shared responsibility model.

1. Is the reasoning described above correct?
2. Does the term _responsibility domain_ capture this notion?

**Comment by sacm** [comment]
Hi Adam,

My two cents.

The noun/adjective "Responsibility" does nothing for me to
disambiguate "Domain".   And the phrase certainly does not
leave any impression of "Boundary" (which seems to be the
important point here).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment]
Thanks, Ira. How about "Boundary of Responsibility" or something similar to that? Or, we can simply leave it at "enterprise boundary".

**Comment by sacm** [comment]
Hi Adam,

Yes, I like "Boundary of Responsibility".

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment]
Any other comments on "boundary of responsibility"? If there are no objections, we'll move forward with this term.

**Comment by wmunyan** [comment]
Well, no other responses.  "Boundary of Responsibility" it is - changed for -04
