### ISSUE TITLE
Define SIEM/SOAR

### ISSUE THREAD

**Issue by wmunyan** [sacmwg/draft-ietf-sacm-arch#24]
Add entries in terminology(?) defining SIEM and SOAR, as they're now referenced under Operations/Health Check

**Comment by adammontville** [comment]
Added the following to the yet to be published -14 draft: `Commonly known as Security Orchestration, Automation, and Response. SOAR is an holistic enterprise capability that exists when threat management, automation of security operations, and incident response are well-coordinated across all security program components in a manner minimizing the need for human intervention`
