### ISSUE TITLE
reliable delivery in messaging

### ISSUE THREAD

**Issue by nacho319** [sacmwg/draft-ietf-sacm-arch#26]
Can we bound the "reliable delivery" statement in the document?  After something is potentially off line for a significant amount of time; how much does a provider have to queue?

**Comment by nacho319** [comment]
this is a well known problem, BTW, and we can talk about common solutions; or just write "an out" of dropping or something after some time out

**Comment by adammontville** [comment]
Added the following to the yet to be checked in -14 draft: `The Integration Service's brokering capabilities enable the exchange of various information payloads, orchestration of component capabilities, message routing, and reliable delivery (within reason - either with persistent messaging mechanisms or by utilizing a timeout after a configurable period of time).`
